2025-07-26 21:26:29,636 [INFO] aiogram.dispatcher: Start polling
2025-07-26 21:26:29,709 [INFO] aiogram.dispatcher: Run polling for bot @hitorilinkbot id=8095484243 - 'HitoriLink'
2025-07-26 21:26:32,281 [WARNING] aiogram.dispatcher: Received SIGINT signal
2025-07-26 21:26:32,282 [INFO] aiogram.dispatcher: Polling stopped for bot @hitorilinkbot id=8095484243 - 'HitoriLink'
2025-07-26 21:26:32,282 [INFO] aiogram.dispatcher: Polling stopped
2025-07-26 21:28:28,121 [INFO] aiogram.dispatcher: Start polling
2025-07-26 21:28:28,194 [INFO] aiogram.dispatcher: Run polling for bot @hitorilinkbot id=8095484243 - 'HitoriLink'
2025-07-26 21:28:44,334 [INFO] root: Created user: <Created (updated) profile:
Name: Unit-NOIR.47-Fade	Age: None
Bio: None

Interests: []
Rating: 1.00 points
Created: 2025-07-26 18:28:44.324756
Updated: 2025-07-26 18:28:44.324766
>
2025-07-26 21:28:45,324 [INFO] aiogram.event: Update id=950880378 is handled. Duration 1073 ms by bot id=8095484243
2025-07-26 21:28:47,040 [INFO] root: User 6907794450 agreed to terms
2025-07-26 21:28:47,329 [INFO] aiogram.event: Update id=950880379 is handled. Duration 299 ms by bot id=8095484243
2025-07-26 21:28:49,095 [INFO] aiogram.event: Update id=950880380 is handled. Duration 107 ms by bot id=8095484243
2025-07-26 21:28:50,394 [INFO] aiogram.event: Update id=950880381 is handled. Duration 145 ms by bot id=8095484243
2025-07-26 21:28:52,440 [INFO] aiogram.event: Update id=950880382 is handled. Duration 98 ms by bot id=8095484243
2025-07-26 21:28:54,420 [INFO] aiogram.event: Update id=950880383 is handled. Duration 98 ms by bot id=8095484243
2025-07-26 21:28:55,731 [INFO] aiogram.event: Update id=950880384 is handled. Duration 172 ms by bot id=8095484243
2025-07-26 21:28:56,405 [INFO] aiogram.event: Update id=950880385 is handled. Duration 231 ms by bot id=8095484243
2025-07-26 21:29:02,638 [INFO] aiogram.event: Update id=950880386 is handled. Duration 107 ms by bot id=8095484243
2025-07-26 21:29:05,221 [INFO] aiogram.event: Update id=950880387 is handled. Duration 333 ms by bot id=8095484243
2025-07-26 21:29:06,633 [INFO] aiogram.event: Update id=950880388 is handled. Duration 281 ms by bot id=8095484243
2025-07-26 21:29:10,267 [INFO] root: User 6907794450 profile_complete=True
2025-07-26 21:29:10,371 [INFO] aiogram.event: Update id=950880389 is handled. Duration 117 ms by bot id=8095484243
2025-07-26 21:29:13,850 [INFO] aiogram.event: Update id=950880390 is handled. Duration 201 ms by bot id=8095484243
2025-07-26 21:29:14,949 [INFO] root: User 6907794450 profile_complete=True
2025-07-26 21:29:15,072 [INFO] aiogram.event: Update id=950880391 is handled. Duration 130 ms by bot id=8095484243
2025-07-26 21:29:17,359 [INFO] aiogram.event: Update id=950880392 is handled. Duration 135 ms by bot id=8095484243
2025-07-26 21:29:26,818 [INFO] root: User 6907794450 profile_complete=True
2025-07-26 21:29:26,926 [INFO] aiogram.event: Update id=950880393 is handled. Duration 120 ms by bot id=8095484243
2025-07-26 21:29:28,687 [INFO] aiogram.event: Update id=950880394 is handled. Duration 212 ms by bot id=8095484243
2025-07-26 21:29:30,153 [INFO] root: User 6907794450 profile_complete=True
2025-07-26 21:29:30,160 [INFO] aiogram.event: Update id=950880395 is not handled. Duration 23 ms by bot id=8095484243
2025-07-26 21:29:30,160 [ERROR] aiogram.event: Cause exception while process update id=950880395 by bot id=8095484243
ValueError: Invalid data: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.CheckViolationError'>: new row for relation "users" violates check constraint "check_age_valid"
DETAIL:  Failing row contains (1, 6907794450, uylag, Unit-NOIR.47-Fade, 14, fdsfsfsfdfds, ["Природа"], [{"type": "photo", "file_id": "AgACAgIAAxkBAAIExmiFHm5rTV4TX__Zl..., t, 1.00, t, null, 2025-07-26 18:28:44.324756, 2025-07-26 18:29:30.157349, f).
[SQL: UPDATE users SET age_required=$1::INTEGER, updated_at=$2::TIMESTAMP WITHOUT TIME ZONE WHERE users.id = $3::INTEGER]
[parameters: (14, datetime.datetime(2025, 7, 26, 18, 29, 30, 157349), 1)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 545, in _prepare_and_execute
    self._rows = deque(await prepared_stmt.fetch(*parameters))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/asyncpg/prepared_stmt.py", line 267, in __bind_execute
    data, status, _ = await self.__do_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
        lambda protocol: protocol.bind_execute(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            self._state, args, '', limit, True, timeout))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/asyncpg/prepared_stmt.py", line 256, in __do_execute
    return await executor(protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 206, in bind_execute
asyncpg.exceptions.CheckViolationError: new row for relation "users" violates check constraint "check_age_valid"
DETAIL:  Failing row contains (1, 6907794450, uylag, Unit-NOIR.47-Fade, 14, fdsfsfsfdfds, ["Природа"], [{"type": "photo", "file_id": "AgACAgIAAxkBAAIExmiFHm5rTV4TX__Zl..., t, 1.00, t, null, 2025-07-26 18:28:44.324756, 2025-07-26 18:29:30.157349, f).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 580, in execute
    self._adapt_connection.await_(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._prepare_and_execute(operation, parameters)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 558, in _prepare_and_execute
    self._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 508, in _handle_exception
    self._adapt_connection._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 792, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.IntegrityError: <class 'asyncpg.exceptions.CheckViolationError'>: new row for relation "users" violates check constraint "check_age_valid"
DETAIL:  Failing row contains (1, 6907794450, uylag, Unit-NOIR.47-Fade, 14, fdsfsfsfdfds, ["Природа"], [{"type": "photo", "file_id": "AgACAgIAAxkBAAIExmiFHm5rTV4TX__Zl..., t, 1.00, t, null, 2025-07-26 18:28:44.324756, 2025-07-26 18:29:30.157349, f).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/db/crud/users.py", line 209, in crr
    await self.session.commit()
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/ext/asyncio/session.py", line 1014, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 4480, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        update,
        ^^^^^^^
    )
    ^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        statement, multiparams, execution_options=execution_options
    )
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 580, in execute
    self._adapt_connection.await_(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._prepare_and_execute(operation, parameters)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 558, in _prepare_and_execute
    self._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 508, in _handle_exception
    self._adapt_connection._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 792, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.CheckViolationError'>: new row for relation "users" violates check constraint "check_age_valid"
DETAIL:  Failing row contains (1, 6907794450, uylag, Unit-NOIR.47-Fade, 14, fdsfsfsfdfds, ["Природа"], [{"type": "photo", "file_id": "AgACAgIAAxkBAAIExmiFHm5rTV4TX__Zl..., t, 1.00, t, null, 2025-07-26 18:28:44.324756, 2025-07-26 18:29:30.157349, f).
[SQL: UPDATE users SET age_required=$1::INTEGER, updated_at=$2::TIMESTAMP WITHOUT TIME ZONE WHERE users.id = $3::INTEGER]
[parameters: (14, datetime.datetime(2025, 7, 26, 18, 29, 30, 157349), 1)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/middlewares/banned_out_mw.py", line 22, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/middlewares/tac_mw.py", line 66, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        observer=observer, update_type=update_type, event=telegram_event, **data
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        observer=observer, update_type=update_type, event=telegram_event, **data
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/.venv/lib/python3.13/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/handlers/edit_handlers.py", line 77, in process_edit_age_required
    await upd.age(age=age)
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/db/crud/users.py", line 230, in age
    return await self.update(age_required=age)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/db/crud/users.py", line 221, in update
    return await self.crr()
           ^^^^^^^^^^^^^^^^
  File "/home/kiyoshima/All_Work_Folders/Projects/PythonProjects/Bots/HitoriLink/db/crud/users.py", line 212, in crr
    raise ValueError(f"Invalid data: {str(e)}")
ValueError: Invalid data: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.CheckViolationError'>: new row for relation "users" violates check constraint "check_age_valid"
DETAIL:  Failing row contains (1, 6907794450, uylag, Unit-NOIR.47-Fade, 14, fdsfsfsfdfds, ["Природа"], [{"type": "photo", "file_id": "AgACAgIAAxkBAAIExmiFHm5rTV4TX__Zl..., t, 1.00, t, null, 2025-07-26 18:28:44.324756, 2025-07-26 18:29:30.157349, f).
[SQL: UPDATE users SET age_required=$1::INTEGER, updated_at=$2::TIMESTAMP WITHOUT TIME ZONE WHERE users.id = $3::INTEGER]
[parameters: (14, datetime.datetime(2025, 7, 26, 18, 29, 30, 157349), 1)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-07-26 21:29:59,832 [INFO] aiogram.event: Update id=950880396 is handled. Duration 279 ms by bot id=8095484243
2025-07-26 21:31:43,017 [WARNING] aiogram.dispatcher: Received SIGINT signal
2025-07-26 21:31:43,019 [INFO] aiogram.dispatcher: Polling stopped for bot @hitorilinkbot id=8095484243 - 'HitoriLink'
2025-07-26 21:31:43,020 [INFO] aiogram.dispatcher: Polling stopped
2025-07-26 21:31:51,982 [INFO] aiogram.dispatcher: Start polling
2025-07-26 21:31:52,058 [INFO] aiogram.dispatcher: Run polling for bot @hitorilinkbot id=8095484243 - 'HitoriLink'
2025-07-26 21:31:53,165 [INFO] root: User 6907794450 profile_complete=True
2025-07-26 21:31:53,879 [INFO] aiogram.event: Update id=950880397 is handled. Duration 782 ms by bot id=8095484243
2025-07-26 21:31:56,155 [INFO] aiogram.event: Update id=950880398 is handled. Duration 196 ms by bot id=8095484243
2025-07-26 21:31:57,373 [INFO] root: User 6907794450 profile_complete=True
2025-07-26 21:31:57,497 [INFO] aiogram.event: Update id=950880399 is handled. Duration 135 ms by bot id=8095484243
2025-07-26 21:32:00,088 [INFO] root: User 6907794450 profile_complete=True
2025-07-26 21:32:00,189 [INFO] aiogram.event: Update id=950880400 is handled. Duration 112 ms by bot id=8095484243
2025-07-26 21:32:01,769 [INFO] aiogram.event: Update id=950880401 is handled. Duration 188 ms by bot id=8095484243
2025-07-26 21:32:03,139 [INFO] root: User 6907794450 profile_complete=True
2025-07-26 21:32:03,270 [INFO] aiogram.event: Update id=950880402 is handled. Duration 148 ms by bot id=8095484243
2025-07-26 21:36:42,267 [WARNING] aiogram.dispatcher: Received SIGINT signal
2025-07-26 21:36:42,268 [INFO] aiogram.dispatcher: Polling stopped for bot @hitorilinkbot id=8095484243 - 'HitoriLink'
2025-07-26 21:36:42,269 [INFO] aiogram.dispatcher: Polling stopped
2025-07-26 21:36:49,528 [INFO] aiogram.dispatcher: Start polling
2025-07-26 21:36:49,604 [INFO] aiogram.dispatcher: Run polling for bot @hitorilinkbot id=8095484243 - 'HitoriLink'
2025-07-26 21:36:57,491 [INFO] root: User 6907794450 profile_complete=True
2025-07-26 21:36:57,492 [INFO] root: /search by 6907794450
2025-07-26 21:36:58,292 [INFO] sentence_transformers.SentenceTransformer: Use pytorch device_name: cpu
2025-07-26 21:36:58,292 [INFO] sentence_transformers.SentenceTransformer: Load pretrained SentenceTransformer: paraphrase-multilingual-mpnet-base-v2
2025-07-26 21:37:03,584 [INFO] root: No more matches for 6907794450
2025-07-26 21:37:03,788 [INFO] aiogram.event: Update id=950880403 is handled. Duration 6372 ms by bot id=8095484243
2025-07-26 21:39:16,377 [INFO] root: Created user: <Created (updated) profile:
Name: в токио утро.	Age: None
Bio: None

Interests: []
Rating: 1.00 points
Created: 2025-07-26 18:39:16.365861
Updated: 2025-07-26 18:39:16.365881
>
2025-07-26 21:39:17,399 [INFO] aiogram.event: Update id=950880404 is handled. Duration 1041 ms by bot id=8095484243
2025-07-26 21:39:18,130 [INFO] root: User 1032263230 agreed to terms
2025-07-26 21:39:18,405 [INFO] aiogram.event: Update id=950880405 is handled. Duration 289 ms by bot id=8095484243
2025-07-26 21:39:19,564 [INFO] aiogram.event: Update id=950880406 is handled. Duration 97 ms by bot id=8095484243
2025-07-26 21:39:20,797 [INFO] aiogram.event: Update id=950880407 is handled. Duration 118 ms by bot id=8095484243
2025-07-26 21:39:23,638 [INFO] aiogram.event: Update id=950880408 is handled. Duration 96 ms by bot id=8095484243
2025-07-26 21:39:24,267 [INFO] aiogram.event: Update id=950880409 is handled. Duration 110 ms by bot id=8095484243
2025-07-26 21:39:27,327 [INFO] aiogram.event: Update id=950880410 is handled. Duration 215 ms by bot id=8095484243
2025-07-26 21:39:32,695 [INFO] aiogram.event: Update id=950880411 is handled. Duration 182 ms by bot id=8095484243
2025-07-26 21:39:35,147 [INFO] aiogram.event: Update id=950880412 is handled. Duration 175 ms by bot id=8095484243
2025-07-26 21:39:35,701 [INFO] aiogram.event: Update id=950880413 is handled. Duration 177 ms by bot id=8095484243
2025-07-26 21:39:38,798 [INFO] aiogram.event: Update id=950880414 is handled. Duration 436 ms by bot id=8095484243
2025-07-26 21:39:41,988 [INFO] aiogram.event: Update id=950880415 is handled. Duration 316 ms by bot id=8095484243
2025-07-26 21:39:43,089 [INFO] aiogram.event: Update id=950880416 is handled. Duration 193 ms by bot id=8095484243
2025-07-26 21:39:44,393 [INFO] aiogram.event: Update id=950880417 is handled. Duration 167 ms by bot id=8095484243
2025-07-26 21:39:45,349 [INFO] aiogram.event: Update id=950880418 is handled. Duration 180 ms by bot id=8095484243
2025-07-26 21:39:49,006 [INFO] aiogram.event: Update id=950880419 is handled. Duration 172 ms by bot id=8095484243
2025-07-26 21:39:49,431 [INFO] aiogram.event: Update id=950880420 is handled. Duration 187 ms by bot id=8095484243
2025-07-26 21:39:57,424 [INFO] aiogram.event: Update id=950880421 is handled. Duration 190 ms by bot id=8095484243
2025-07-26 21:39:59,802 [INFO] aiogram.event: Update id=950880422 is handled. Duration 613 ms by bot id=8095484243
2025-07-26 21:40:02,978 [INFO] aiogram.event: Update id=950880423 is handled. Duration 1536 ms by bot id=8095484243
2025-07-26 21:40:13,935 [INFO] root: User 1032263230 profile_complete=True
2025-07-26 21:40:13,936 [INFO] root: /search by 1032263230
2025-07-26 21:40:14,380 [INFO] sentence_transformers.SentenceTransformer: Use pytorch device_name: cpu
2025-07-26 21:40:14,381 [INFO] sentence_transformers.SentenceTransformer: Load pretrained SentenceTransformer: paraphrase-multilingual-mpnet-base-v2
2025-07-26 21:40:19,778 [INFO] aiogram.event: Update id=950880424 is handled. Duration 5855 ms by bot id=8095484243
2025-07-26 21:40:29,193 [INFO] root: User 1032263230 profile_complete=True
2025-07-26 21:40:29,194 [INFO] root: Next match request by 1032263230
2025-07-26 21:40:29,333 [INFO] sentence_transformers.SentenceTransformer: Use pytorch device_name: cpu
2025-07-26 21:40:29,333 [INFO] sentence_transformers.SentenceTransformer: Load pretrained SentenceTransformer: paraphrase-multilingual-mpnet-base-v2
2025-07-26 21:40:34,015 [INFO] root: No more matches for 1032263230
2025-07-26 21:40:34,412 [INFO] aiogram.event: Update id=950880425 is handled. Duration 5231 ms by bot id=8095484243
2025-07-26 21:40:43,017 [INFO] root: User 1032263230 profile_complete=True
2025-07-26 21:40:43,018 [INFO] root: /search by 1032263230
2025-07-26 21:40:43,115 [INFO] sentence_transformers.SentenceTransformer: Use pytorch device_name: cpu
2025-07-26 21:40:43,116 [INFO] sentence_transformers.SentenceTransformer: Load pretrained SentenceTransformer: paraphrase-multilingual-mpnet-base-v2
2025-07-26 21:40:48,333 [INFO] aiogram.event: Update id=950880426 is handled. Duration 5326 ms by bot id=8095484243
2025-07-26 21:40:49,778 [INFO] root: User 1032263230 profile_complete=True
2025-07-26 21:40:49,781 [INFO] root: Оплата успешна: 1032263230 купил контакт @uylag
2025-07-26 21:40:49,875 [INFO] aiogram.event: Update id=950880427 is handled. Duration 107 ms by bot id=8095484243
2025-07-28 00:08:02,993 [ERROR] aiogram.dispatcher: Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2025-07-28 00:08:02,997 [WARNING] aiogram.dispatcher: Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8095484243)
2025-07-28 00:08:14,742 [INFO] aiogram.dispatcher: Connection established (tryings = 1, bot id = 8095484243)
2025-07-28 01:26:53,344 [WARNING] aiogram.dispatcher: Received SIGINT signal
2025-07-28 01:26:53,360 [INFO] aiogram.dispatcher: Polling stopped for bot @hitorilinkbot id=8095484243 - 'HitoriLink'
2025-07-28 01:26:53,361 [INFO] aiogram.dispatcher: Polling stopped
